name = "Qrochet"
uuid = "881a8f22-b5d0-48b0-96e5-a244b33f36d4"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Muscle = "21fe5c4b-a943-414d-bf3e-516f24900631"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tenet = "85d41934-b9cd-44e1-8730-56d86f15f3ec"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
Quac = "b9105292-1415-45cf-bff1-d6ccf71e6143"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[extensions]
QrochetAdaptExt = "Adapt"
QrochetChainRulesCoreExt = "ChainRulesCore"
QrochetChainRulesTestUtilsExt = ["ChainRulesCore", "ChainRulesTestUtils"]
QrochetQuacExt = "Quac"
QrochetYaoExt = "Yao"

[compat]
ChainRulesCore = "1.0"
ChainRulesTestUtils = "1"
Muscle = "0.2"
Quac = "0.3"
Tenet = "0.6"
Yao = "0.8, 0.9"
julia = "1.9"
