name = "Qrochet"
uuid = "881a8f22-b5d0-48b0-96e5-a244b33f36d4"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.1.0"

[deps]
Tenet = "85d41934-b9cd-44e1-8730-56d86f15f3ec"

[compat]
Tenet = "0.3"
julia = "1.9"
