name = "Qrochet"
uuid = "881a8f22-b5d0-48b0-96e5-a244b33f36d4"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez+git@bsc.es>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Muscle = "21fe5c4b-a943-414d-bf3e-516f24900631"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tenet = "85d41934-b9cd-44e1-8730-56d86f15f3ec"
ValSplit = "0625e100-946b-11ec-09cd-6328dd093154"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
Quac = "b9105292-1415-45cf-bff1-d6ccf71e6143"

[extensions]
QrochetChainRulesCoreExt = "ChainRulesCore"
QrochetChainRulesTestUtilsExt = ["ChainRulesCore", "ChainRulesTestUtils"]
QrochetQuacExt = "Quac"

[compat]
ChainRulesCore = "1.0"
Muscle = "0.1"
Quac = "0.3"
Tenet = "0.5"
ValSplit = "0.1"
julia = "1.9"
